USE [AnirbanDB]
GO
DELETE FROM [dbo].[EMD_EMPLOYEE_DETAILS];
DBCC CHECKIDENT ('EMD_EMPLOYEE_DETAILS', RESEED, 0);
DELETE FROM [dbo].[EMP_EMPLOYEE];
DBCC CHECKIDENT ('EMP_EMPLOYEE', RESEED, 0);
DELETE FROM [dbo].[DEP_DEPARTMENT];
DBCC CHECKIDENT ('DEP_DEPARTMENT', RESEED, 0);
DELETE FROM [dbo].[COU_COUNTRY];
DBCC CHECKIDENT ('COU_COUNTRY', RESEED, 0);

GO